# Generated by Django 3.2.7 on 2022-02-25 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_detail_menu_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='table',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
