# Generated by Django 3.2.7 on 2022-02-26 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220226_1007'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detail',
            table='detail',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
    ]
