# Generated by Django 3.2.7 on 2022-02-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8)),
                ('role', models.CharField(choices=[('Cashier', 'Cashier'), ('Supervisor', 'Supervisor'), ('Admin', 'Admin')], default='Cashier', max_length=10)),
            ],
        ),
    ]
